name: Tests
on:
  pull_request:
    branches:
      - "*"
      - "!gitbook"

jobs:
  Linting:
    runs-on: macOS-15
    steps:
      - uses: actions/checkout@v3
      - name: Install swift-format
        run: brew install swift-format
      - name: Linting
        run: swift-format lint -r -s ./CodeApp ./Extensions ./CodeUITests
      - name: Unit Tests
        run: fastlane tests
        env:
          XCODE_PATH: "/Applications/Xcode_16.4.app"
